language: csharp
solution: TPO_Lab2.sln
install:
  - nuget restore TPO_Lab2.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release TPO_Lab2.sln

